name: Test

on:
  push:
    branches:
    - master
    paths-ignore:
    - '*.md'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '*.md'

jobs:
  test:
    strategy:
      matrix:
        node: ['6.x', '8.x', '10.x', '12.x', '14.x', '16.x']
    runs-on: ubuntu-latest
    steps:
    - uses:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install # switch to 'npm ci' when min node is >=10
    - run: npm test
